package com.example.hxyz.domain.entity;

import java.util.Date;

public class FactoryUserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer f_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_factory_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer f_factory_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_factory_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_factory_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_username
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_mobile
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_device_code
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_device_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_password
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_photo
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_realname
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_title
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_role
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_status
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer f_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_factory_type
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_factory_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_charge_factorys
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_charge_factorys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_check_step
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_check_step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_joined_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date f_joined_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_work_begin_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date f_work_begin_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_work_end_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date f_work_end_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_break_address
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_break_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_break_fee
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Double f_break_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_card_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_card_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_citizen_id_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_citizen_id_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_citizen_id_img1
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_citizen_id_img1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_citizen_id_img2
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_citizen_id_img2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_creator_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer f_creator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_create_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date f_create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_recruitment_person
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_recruitment_person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_factory_user.f_recruitment_path
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String f_recruitment_path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_id
     *
     * @return the value of t_factory_user.f_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getF_id() {
        return f_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_id
     *
     * @param f_id the value for t_factory_user.f_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_id(Integer f_id) {
        this.f_id = f_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_factory_id
     *
     * @return the value of t_factory_user.f_factory_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getF_factory_id() {
        return f_factory_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_factory_id
     *
     * @param f_factory_id the value for t_factory_user.f_factory_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_factory_id(Integer f_factory_id) {
        this.f_factory_id = f_factory_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_factory_name
     *
     * @return the value of t_factory_user.f_factory_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_factory_name() {
        return f_factory_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_factory_name
     *
     * @param f_factory_name the value for t_factory_user.f_factory_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_factory_name(String f_factory_name) {
        this.f_factory_name = f_factory_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_username
     *
     * @return the value of t_factory_user.f_username
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_username() {
        return f_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_username
     *
     * @param f_username the value for t_factory_user.f_username
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_username(String f_username) {
        this.f_username = f_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_mobile
     *
     * @return the value of t_factory_user.f_mobile
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_mobile() {
        return f_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_mobile
     *
     * @param f_mobile the value for t_factory_user.f_mobile
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_mobile(String f_mobile) {
        this.f_mobile = f_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_device_code
     *
     * @return the value of t_factory_user.f_device_code
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_device_code() {
        return f_device_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_device_code
     *
     * @param f_device_code the value for t_factory_user.f_device_code
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_device_code(String f_device_code) {
        this.f_device_code = f_device_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_password
     *
     * @return the value of t_factory_user.f_password
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_password() {
        return f_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_password
     *
     * @param f_password the value for t_factory_user.f_password
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_password(String f_password) {
        this.f_password = f_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_photo
     *
     * @return the value of t_factory_user.f_photo
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_photo() {
        return f_photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_photo
     *
     * @param f_photo the value for t_factory_user.f_photo
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_photo(String f_photo) {
        this.f_photo = f_photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_realname
     *
     * @return the value of t_factory_user.f_realname
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_realname() {
        return f_realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_realname
     *
     * @param f_realname the value for t_factory_user.f_realname
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_realname(String f_realname) {
        this.f_realname = f_realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_title
     *
     * @return the value of t_factory_user.f_title
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_title() {
        return f_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_title
     *
     * @param f_title the value for t_factory_user.f_title
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_title(String f_title) {
        this.f_title = f_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_role
     *
     * @return the value of t_factory_user.f_role
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_role() {
        return f_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_role
     *
     * @param f_role the value for t_factory_user.f_role
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_role(String f_role) {
        this.f_role = f_role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_status
     *
     * @return the value of t_factory_user.f_status
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getF_status() {
        return f_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_status
     *
     * @param f_status the value for t_factory_user.f_status
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_status(Integer f_status) {
        this.f_status = f_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_factory_type
     *
     * @return the value of t_factory_user.f_factory_type
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_factory_type() {
        return f_factory_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_factory_type
     *
     * @param f_factory_type the value for t_factory_user.f_factory_type
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_factory_type(String f_factory_type) {
        this.f_factory_type = f_factory_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_charge_factorys
     *
     * @return the value of t_factory_user.f_charge_factorys
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_charge_factorys() {
        return f_charge_factorys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_charge_factorys
     *
     * @param f_charge_factorys the value for t_factory_user.f_charge_factorys
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_charge_factorys(String f_charge_factorys) {
        this.f_charge_factorys = f_charge_factorys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_check_step
     *
     * @return the value of t_factory_user.f_check_step
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_check_step() {
        return f_check_step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_check_step
     *
     * @param f_check_step the value for t_factory_user.f_check_step
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_check_step(String f_check_step) {
        this.f_check_step = f_check_step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_joined_date
     *
     * @return the value of t_factory_user.f_joined_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getF_joined_date() {
        return f_joined_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_joined_date
     *
     * @param f_joined_date the value for t_factory_user.f_joined_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_joined_date(Date f_joined_date) {
        this.f_joined_date = f_joined_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_work_begin_date
     *
     * @return the value of t_factory_user.f_work_begin_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getF_work_begin_date() {
        return f_work_begin_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_work_begin_date
     *
     * @param f_work_begin_date the value for t_factory_user.f_work_begin_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_work_begin_date(Date f_work_begin_date) {
        this.f_work_begin_date = f_work_begin_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_work_end_date
     *
     * @return the value of t_factory_user.f_work_end_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getF_work_end_date() {
        return f_work_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_work_end_date
     *
     * @param f_work_end_date the value for t_factory_user.f_work_end_date
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_work_end_date(Date f_work_end_date) {
        this.f_work_end_date = f_work_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_break_address
     *
     * @return the value of t_factory_user.f_break_address
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_break_address() {
        return f_break_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_break_address
     *
     * @param f_break_address the value for t_factory_user.f_break_address
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_break_address(String f_break_address) {
        this.f_break_address = f_break_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_break_fee
     *
     * @return the value of t_factory_user.f_break_fee
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Double getF_break_fee() {
        return f_break_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_break_fee
     *
     * @param f_break_fee the value for t_factory_user.f_break_fee
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_break_fee(Double f_break_fee) {
        this.f_break_fee = f_break_fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_card_no
     *
     * @return the value of t_factory_user.f_card_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_card_no() {
        return f_card_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_card_no
     *
     * @param f_card_no the value for t_factory_user.f_card_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_card_no(String f_card_no) {
        this.f_card_no = f_card_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_citizen_id_no
     *
     * @return the value of t_factory_user.f_citizen_id_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_citizen_id_no() {
        return f_citizen_id_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_citizen_id_no
     *
     * @param f_citizen_id_no the value for t_factory_user.f_citizen_id_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_citizen_id_no(String f_citizen_id_no) {
        this.f_citizen_id_no = f_citizen_id_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_citizen_id_img1
     *
     * @return the value of t_factory_user.f_citizen_id_img1
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_citizen_id_img1() {
        return f_citizen_id_img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_citizen_id_img1
     *
     * @param f_citizen_id_img1 the value for t_factory_user.f_citizen_id_img1
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_citizen_id_img1(String f_citizen_id_img1) {
        this.f_citizen_id_img1 = f_citizen_id_img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_citizen_id_img2
     *
     * @return the value of t_factory_user.f_citizen_id_img2
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_citizen_id_img2() {
        return f_citizen_id_img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_citizen_id_img2
     *
     * @param f_citizen_id_img2 the value for t_factory_user.f_citizen_id_img2
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_citizen_id_img2(String f_citizen_id_img2) {
        this.f_citizen_id_img2 = f_citizen_id_img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_creator_id
     *
     * @return the value of t_factory_user.f_creator_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getF_creator_id() {
        return f_creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_creator_id
     *
     * @param f_creator_id the value for t_factory_user.f_creator_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_creator_id(Integer f_creator_id) {
        this.f_creator_id = f_creator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_create_time
     *
     * @return the value of t_factory_user.f_create_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getF_create_time() {
        return f_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_create_time
     *
     * @param f_create_time the value for t_factory_user.f_create_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_create_time(Date f_create_time) {
        this.f_create_time = f_create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_recruitment_person
     *
     * @return the value of t_factory_user.f_recruitment_person
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_recruitment_person() {
        return f_recruitment_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_recruitment_person
     *
     * @param f_recruitment_person the value for t_factory_user.f_recruitment_person
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_recruitment_person(String f_recruitment_person) {
        this.f_recruitment_person = f_recruitment_person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_factory_user.f_recruitment_path
     *
     * @return the value of t_factory_user.f_recruitment_path
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getF_recruitment_path() {
        return f_recruitment_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_factory_user.f_recruitment_path
     *
     * @param f_recruitment_path the value for t_factory_user.f_recruitment_path
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setF_recruitment_path(String f_recruitment_path) {
        this.f_recruitment_path = f_recruitment_path;
    }
}