package com.example.hxyz.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FactoryUserEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public FactoryUserEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_idIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andF_idIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_idEqualTo(Integer value) {
            addCriterion("f_id =", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThan(Integer value) {
            addCriterion("f_id >", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThan(Integer value) {
            addCriterion("f_id <", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idIn(List<Integer> values) {
            addCriterion("f_id in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idIsNull() {
            addCriterion("f_factory_id is null");
            return (Criteria) this;
        }

        public Criteria andF_factory_idIsNotNull() {
            addCriterion("f_factory_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_factory_idEqualTo(Integer value) {
            addCriterion("f_factory_id =", value, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idNotEqualTo(Integer value) {
            addCriterion("f_factory_id <>", value, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idGreaterThan(Integer value) {
            addCriterion("f_factory_id >", value, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_factory_id >=", value, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idLessThan(Integer value) {
            addCriterion("f_factory_id <", value, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_factory_id <=", value, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idIn(List<Integer> values) {
            addCriterion("f_factory_id in", values, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idNotIn(List<Integer> values) {
            addCriterion("f_factory_id not in", values, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idBetween(Integer value1, Integer value2) {
            addCriterion("f_factory_id between", value1, value2, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_factory_id not between", value1, value2, "f_factory_id");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameIsNull() {
            addCriterion("f_factory_name is null");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameIsNotNull() {
            addCriterion("f_factory_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameEqualTo(String value) {
            addCriterion("f_factory_name =", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameNotEqualTo(String value) {
            addCriterion("f_factory_name <>", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameGreaterThan(String value) {
            addCriterion("f_factory_name >", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_factory_name >=", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameLessThan(String value) {
            addCriterion("f_factory_name <", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameLessThanOrEqualTo(String value) {
            addCriterion("f_factory_name <=", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameLike(String value) {
            addCriterion("f_factory_name like", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameNotLike(String value) {
            addCriterion("f_factory_name not like", value, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameIn(List<String> values) {
            addCriterion("f_factory_name in", values, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameNotIn(List<String> values) {
            addCriterion("f_factory_name not in", values, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameBetween(String value1, String value2) {
            addCriterion("f_factory_name between", value1, value2, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_factory_nameNotBetween(String value1, String value2) {
            addCriterion("f_factory_name not between", value1, value2, "f_factory_name");
            return (Criteria) this;
        }

        public Criteria andF_usernameIsNull() {
            addCriterion("f_username is null");
            return (Criteria) this;
        }

        public Criteria andF_usernameIsNotNull() {
            addCriterion("f_username is not null");
            return (Criteria) this;
        }

        public Criteria andF_usernameEqualTo(String value) {
            addCriterion("f_username =", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameNotEqualTo(String value) {
            addCriterion("f_username <>", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameGreaterThan(String value) {
            addCriterion("f_username >", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameGreaterThanOrEqualTo(String value) {
            addCriterion("f_username >=", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameLessThan(String value) {
            addCriterion("f_username <", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameLessThanOrEqualTo(String value) {
            addCriterion("f_username <=", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameLike(String value) {
            addCriterion("f_username like", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameNotLike(String value) {
            addCriterion("f_username not like", value, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameIn(List<String> values) {
            addCriterion("f_username in", values, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameNotIn(List<String> values) {
            addCriterion("f_username not in", values, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameBetween(String value1, String value2) {
            addCriterion("f_username between", value1, value2, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_usernameNotBetween(String value1, String value2) {
            addCriterion("f_username not between", value1, value2, "f_username");
            return (Criteria) this;
        }

        public Criteria andF_mobileIsNull() {
            addCriterion("f_mobile is null");
            return (Criteria) this;
        }

        public Criteria andF_mobileIsNotNull() {
            addCriterion("f_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andF_mobileEqualTo(String value) {
            addCriterion("f_mobile =", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileNotEqualTo(String value) {
            addCriterion("f_mobile <>", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileGreaterThan(String value) {
            addCriterion("f_mobile >", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileGreaterThanOrEqualTo(String value) {
            addCriterion("f_mobile >=", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileLessThan(String value) {
            addCriterion("f_mobile <", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileLessThanOrEqualTo(String value) {
            addCriterion("f_mobile <=", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileLike(String value) {
            addCriterion("f_mobile like", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileNotLike(String value) {
            addCriterion("f_mobile not like", value, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileIn(List<String> values) {
            addCriterion("f_mobile in", values, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileNotIn(List<String> values) {
            addCriterion("f_mobile not in", values, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileBetween(String value1, String value2) {
            addCriterion("f_mobile between", value1, value2, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_mobileNotBetween(String value1, String value2) {
            addCriterion("f_mobile not between", value1, value2, "f_mobile");
            return (Criteria) this;
        }

        public Criteria andF_device_codeIsNull() {
            addCriterion("f_device_code is null");
            return (Criteria) this;
        }

        public Criteria andF_device_codeIsNotNull() {
            addCriterion("f_device_code is not null");
            return (Criteria) this;
        }

        public Criteria andF_device_codeEqualTo(String value) {
            addCriterion("f_device_code =", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeNotEqualTo(String value) {
            addCriterion("f_device_code <>", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeGreaterThan(String value) {
            addCriterion("f_device_code >", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeGreaterThanOrEqualTo(String value) {
            addCriterion("f_device_code >=", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeLessThan(String value) {
            addCriterion("f_device_code <", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeLessThanOrEqualTo(String value) {
            addCriterion("f_device_code <=", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeLike(String value) {
            addCriterion("f_device_code like", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeNotLike(String value) {
            addCriterion("f_device_code not like", value, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeIn(List<String> values) {
            addCriterion("f_device_code in", values, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeNotIn(List<String> values) {
            addCriterion("f_device_code not in", values, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeBetween(String value1, String value2) {
            addCriterion("f_device_code between", value1, value2, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_device_codeNotBetween(String value1, String value2) {
            addCriterion("f_device_code not between", value1, value2, "f_device_code");
            return (Criteria) this;
        }

        public Criteria andF_passwordIsNull() {
            addCriterion("f_password is null");
            return (Criteria) this;
        }

        public Criteria andF_passwordIsNotNull() {
            addCriterion("f_password is not null");
            return (Criteria) this;
        }

        public Criteria andF_passwordEqualTo(String value) {
            addCriterion("f_password =", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotEqualTo(String value) {
            addCriterion("f_password <>", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordGreaterThan(String value) {
            addCriterion("f_password >", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordGreaterThanOrEqualTo(String value) {
            addCriterion("f_password >=", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordLessThan(String value) {
            addCriterion("f_password <", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordLessThanOrEqualTo(String value) {
            addCriterion("f_password <=", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordLike(String value) {
            addCriterion("f_password like", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotLike(String value) {
            addCriterion("f_password not like", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordIn(List<String> values) {
            addCriterion("f_password in", values, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotIn(List<String> values) {
            addCriterion("f_password not in", values, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordBetween(String value1, String value2) {
            addCriterion("f_password between", value1, value2, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotBetween(String value1, String value2) {
            addCriterion("f_password not between", value1, value2, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_photoIsNull() {
            addCriterion("f_photo is null");
            return (Criteria) this;
        }

        public Criteria andF_photoIsNotNull() {
            addCriterion("f_photo is not null");
            return (Criteria) this;
        }

        public Criteria andF_photoEqualTo(String value) {
            addCriterion("f_photo =", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoNotEqualTo(String value) {
            addCriterion("f_photo <>", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoGreaterThan(String value) {
            addCriterion("f_photo >", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoGreaterThanOrEqualTo(String value) {
            addCriterion("f_photo >=", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoLessThan(String value) {
            addCriterion("f_photo <", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoLessThanOrEqualTo(String value) {
            addCriterion("f_photo <=", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoLike(String value) {
            addCriterion("f_photo like", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoNotLike(String value) {
            addCriterion("f_photo not like", value, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoIn(List<String> values) {
            addCriterion("f_photo in", values, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoNotIn(List<String> values) {
            addCriterion("f_photo not in", values, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoBetween(String value1, String value2) {
            addCriterion("f_photo between", value1, value2, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_photoNotBetween(String value1, String value2) {
            addCriterion("f_photo not between", value1, value2, "f_photo");
            return (Criteria) this;
        }

        public Criteria andF_realnameIsNull() {
            addCriterion("f_realname is null");
            return (Criteria) this;
        }

        public Criteria andF_realnameIsNotNull() {
            addCriterion("f_realname is not null");
            return (Criteria) this;
        }

        public Criteria andF_realnameEqualTo(String value) {
            addCriterion("f_realname =", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameNotEqualTo(String value) {
            addCriterion("f_realname <>", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameGreaterThan(String value) {
            addCriterion("f_realname >", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameGreaterThanOrEqualTo(String value) {
            addCriterion("f_realname >=", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameLessThan(String value) {
            addCriterion("f_realname <", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameLessThanOrEqualTo(String value) {
            addCriterion("f_realname <=", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameLike(String value) {
            addCriterion("f_realname like", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameNotLike(String value) {
            addCriterion("f_realname not like", value, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameIn(List<String> values) {
            addCriterion("f_realname in", values, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameNotIn(List<String> values) {
            addCriterion("f_realname not in", values, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameBetween(String value1, String value2) {
            addCriterion("f_realname between", value1, value2, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_realnameNotBetween(String value1, String value2) {
            addCriterion("f_realname not between", value1, value2, "f_realname");
            return (Criteria) this;
        }

        public Criteria andF_titleIsNull() {
            addCriterion("f_title is null");
            return (Criteria) this;
        }

        public Criteria andF_titleIsNotNull() {
            addCriterion("f_title is not null");
            return (Criteria) this;
        }

        public Criteria andF_titleEqualTo(String value) {
            addCriterion("f_title =", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotEqualTo(String value) {
            addCriterion("f_title <>", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleGreaterThan(String value) {
            addCriterion("f_title >", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleGreaterThanOrEqualTo(String value) {
            addCriterion("f_title >=", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLessThan(String value) {
            addCriterion("f_title <", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLessThanOrEqualTo(String value) {
            addCriterion("f_title <=", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLike(String value) {
            addCriterion("f_title like", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotLike(String value) {
            addCriterion("f_title not like", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleIn(List<String> values) {
            addCriterion("f_title in", values, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotIn(List<String> values) {
            addCriterion("f_title not in", values, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleBetween(String value1, String value2) {
            addCriterion("f_title between", value1, value2, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotBetween(String value1, String value2) {
            addCriterion("f_title not between", value1, value2, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_roleIsNull() {
            addCriterion("f_role is null");
            return (Criteria) this;
        }

        public Criteria andF_roleIsNotNull() {
            addCriterion("f_role is not null");
            return (Criteria) this;
        }

        public Criteria andF_roleEqualTo(String value) {
            addCriterion("f_role =", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleNotEqualTo(String value) {
            addCriterion("f_role <>", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleGreaterThan(String value) {
            addCriterion("f_role >", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleGreaterThanOrEqualTo(String value) {
            addCriterion("f_role >=", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleLessThan(String value) {
            addCriterion("f_role <", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleLessThanOrEqualTo(String value) {
            addCriterion("f_role <=", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleLike(String value) {
            addCriterion("f_role like", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleNotLike(String value) {
            addCriterion("f_role not like", value, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleIn(List<String> values) {
            addCriterion("f_role in", values, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleNotIn(List<String> values) {
            addCriterion("f_role not in", values, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleBetween(String value1, String value2) {
            addCriterion("f_role between", value1, value2, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_roleNotBetween(String value1, String value2) {
            addCriterion("f_role not between", value1, value2, "f_role");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andF_statusEqualTo(Integer value) {
            addCriterion("f_status =", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThan(Integer value) {
            addCriterion("f_status <", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusIn(List<Integer> values) {
            addCriterion("f_status in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeIsNull() {
            addCriterion("f_factory_type is null");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeIsNotNull() {
            addCriterion("f_factory_type is not null");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeEqualTo(String value) {
            addCriterion("f_factory_type =", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeNotEqualTo(String value) {
            addCriterion("f_factory_type <>", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeGreaterThan(String value) {
            addCriterion("f_factory_type >", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeGreaterThanOrEqualTo(String value) {
            addCriterion("f_factory_type >=", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeLessThan(String value) {
            addCriterion("f_factory_type <", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeLessThanOrEqualTo(String value) {
            addCriterion("f_factory_type <=", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeLike(String value) {
            addCriterion("f_factory_type like", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeNotLike(String value) {
            addCriterion("f_factory_type not like", value, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeIn(List<String> values) {
            addCriterion("f_factory_type in", values, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeNotIn(List<String> values) {
            addCriterion("f_factory_type not in", values, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeBetween(String value1, String value2) {
            addCriterion("f_factory_type between", value1, value2, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_factory_typeNotBetween(String value1, String value2) {
            addCriterion("f_factory_type not between", value1, value2, "f_factory_type");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysIsNull() {
            addCriterion("f_charge_factorys is null");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysIsNotNull() {
            addCriterion("f_charge_factorys is not null");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysEqualTo(String value) {
            addCriterion("f_charge_factorys =", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysNotEqualTo(String value) {
            addCriterion("f_charge_factorys <>", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysGreaterThan(String value) {
            addCriterion("f_charge_factorys >", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysGreaterThanOrEqualTo(String value) {
            addCriterion("f_charge_factorys >=", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysLessThan(String value) {
            addCriterion("f_charge_factorys <", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysLessThanOrEqualTo(String value) {
            addCriterion("f_charge_factorys <=", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysLike(String value) {
            addCriterion("f_charge_factorys like", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysNotLike(String value) {
            addCriterion("f_charge_factorys not like", value, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysIn(List<String> values) {
            addCriterion("f_charge_factorys in", values, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysNotIn(List<String> values) {
            addCriterion("f_charge_factorys not in", values, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysBetween(String value1, String value2) {
            addCriterion("f_charge_factorys between", value1, value2, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_charge_factorysNotBetween(String value1, String value2) {
            addCriterion("f_charge_factorys not between", value1, value2, "f_charge_factorys");
            return (Criteria) this;
        }

        public Criteria andF_check_stepIsNull() {
            addCriterion("f_check_step is null");
            return (Criteria) this;
        }

        public Criteria andF_check_stepIsNotNull() {
            addCriterion("f_check_step is not null");
            return (Criteria) this;
        }

        public Criteria andF_check_stepEqualTo(String value) {
            addCriterion("f_check_step =", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepNotEqualTo(String value) {
            addCriterion("f_check_step <>", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepGreaterThan(String value) {
            addCriterion("f_check_step >", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepGreaterThanOrEqualTo(String value) {
            addCriterion("f_check_step >=", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepLessThan(String value) {
            addCriterion("f_check_step <", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepLessThanOrEqualTo(String value) {
            addCriterion("f_check_step <=", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepLike(String value) {
            addCriterion("f_check_step like", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepNotLike(String value) {
            addCriterion("f_check_step not like", value, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepIn(List<String> values) {
            addCriterion("f_check_step in", values, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepNotIn(List<String> values) {
            addCriterion("f_check_step not in", values, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepBetween(String value1, String value2) {
            addCriterion("f_check_step between", value1, value2, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_check_stepNotBetween(String value1, String value2) {
            addCriterion("f_check_step not between", value1, value2, "f_check_step");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateIsNull() {
            addCriterion("f_joined_date is null");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateIsNotNull() {
            addCriterion("f_joined_date is not null");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateEqualTo(Date value) {
            addCriterion("f_joined_date =", value, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateNotEqualTo(Date value) {
            addCriterion("f_joined_date <>", value, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateGreaterThan(Date value) {
            addCriterion("f_joined_date >", value, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("f_joined_date >=", value, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateLessThan(Date value) {
            addCriterion("f_joined_date <", value, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateLessThanOrEqualTo(Date value) {
            addCriterion("f_joined_date <=", value, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateIn(List<Date> values) {
            addCriterion("f_joined_date in", values, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateNotIn(List<Date> values) {
            addCriterion("f_joined_date not in", values, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateBetween(Date value1, Date value2) {
            addCriterion("f_joined_date between", value1, value2, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_joined_dateNotBetween(Date value1, Date value2) {
            addCriterion("f_joined_date not between", value1, value2, "f_joined_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateIsNull() {
            addCriterion("f_work_begin_date is null");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateIsNotNull() {
            addCriterion("f_work_begin_date is not null");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateEqualTo(Date value) {
            addCriterion("f_work_begin_date =", value, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateNotEqualTo(Date value) {
            addCriterion("f_work_begin_date <>", value, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateGreaterThan(Date value) {
            addCriterion("f_work_begin_date >", value, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("f_work_begin_date >=", value, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateLessThan(Date value) {
            addCriterion("f_work_begin_date <", value, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateLessThanOrEqualTo(Date value) {
            addCriterion("f_work_begin_date <=", value, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateIn(List<Date> values) {
            addCriterion("f_work_begin_date in", values, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateNotIn(List<Date> values) {
            addCriterion("f_work_begin_date not in", values, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateBetween(Date value1, Date value2) {
            addCriterion("f_work_begin_date between", value1, value2, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_begin_dateNotBetween(Date value1, Date value2) {
            addCriterion("f_work_begin_date not between", value1, value2, "f_work_begin_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateIsNull() {
            addCriterion("f_work_end_date is null");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateIsNotNull() {
            addCriterion("f_work_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateEqualTo(Date value) {
            addCriterion("f_work_end_date =", value, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateNotEqualTo(Date value) {
            addCriterion("f_work_end_date <>", value, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateGreaterThan(Date value) {
            addCriterion("f_work_end_date >", value, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("f_work_end_date >=", value, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateLessThan(Date value) {
            addCriterion("f_work_end_date <", value, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateLessThanOrEqualTo(Date value) {
            addCriterion("f_work_end_date <=", value, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateIn(List<Date> values) {
            addCriterion("f_work_end_date in", values, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateNotIn(List<Date> values) {
            addCriterion("f_work_end_date not in", values, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateBetween(Date value1, Date value2) {
            addCriterion("f_work_end_date between", value1, value2, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_work_end_dateNotBetween(Date value1, Date value2) {
            addCriterion("f_work_end_date not between", value1, value2, "f_work_end_date");
            return (Criteria) this;
        }

        public Criteria andF_break_addressIsNull() {
            addCriterion("f_break_address is null");
            return (Criteria) this;
        }

        public Criteria andF_break_addressIsNotNull() {
            addCriterion("f_break_address is not null");
            return (Criteria) this;
        }

        public Criteria andF_break_addressEqualTo(String value) {
            addCriterion("f_break_address =", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressNotEqualTo(String value) {
            addCriterion("f_break_address <>", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressGreaterThan(String value) {
            addCriterion("f_break_address >", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressGreaterThanOrEqualTo(String value) {
            addCriterion("f_break_address >=", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressLessThan(String value) {
            addCriterion("f_break_address <", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressLessThanOrEqualTo(String value) {
            addCriterion("f_break_address <=", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressLike(String value) {
            addCriterion("f_break_address like", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressNotLike(String value) {
            addCriterion("f_break_address not like", value, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressIn(List<String> values) {
            addCriterion("f_break_address in", values, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressNotIn(List<String> values) {
            addCriterion("f_break_address not in", values, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressBetween(String value1, String value2) {
            addCriterion("f_break_address between", value1, value2, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_addressNotBetween(String value1, String value2) {
            addCriterion("f_break_address not between", value1, value2, "f_break_address");
            return (Criteria) this;
        }

        public Criteria andF_break_feeIsNull() {
            addCriterion("f_break_fee is null");
            return (Criteria) this;
        }

        public Criteria andF_break_feeIsNotNull() {
            addCriterion("f_break_fee is not null");
            return (Criteria) this;
        }

        public Criteria andF_break_feeEqualTo(Double value) {
            addCriterion("f_break_fee =", value, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeNotEqualTo(Double value) {
            addCriterion("f_break_fee <>", value, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeGreaterThan(Double value) {
            addCriterion("f_break_fee >", value, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeGreaterThanOrEqualTo(Double value) {
            addCriterion("f_break_fee >=", value, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeLessThan(Double value) {
            addCriterion("f_break_fee <", value, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeLessThanOrEqualTo(Double value) {
            addCriterion("f_break_fee <=", value, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeIn(List<Double> values) {
            addCriterion("f_break_fee in", values, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeNotIn(List<Double> values) {
            addCriterion("f_break_fee not in", values, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeBetween(Double value1, Double value2) {
            addCriterion("f_break_fee between", value1, value2, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_break_feeNotBetween(Double value1, Double value2) {
            addCriterion("f_break_fee not between", value1, value2, "f_break_fee");
            return (Criteria) this;
        }

        public Criteria andF_card_noIsNull() {
            addCriterion("f_card_no is null");
            return (Criteria) this;
        }

        public Criteria andF_card_noIsNotNull() {
            addCriterion("f_card_no is not null");
            return (Criteria) this;
        }

        public Criteria andF_card_noEqualTo(String value) {
            addCriterion("f_card_no =", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noNotEqualTo(String value) {
            addCriterion("f_card_no <>", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noGreaterThan(String value) {
            addCriterion("f_card_no >", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_card_no >=", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noLessThan(String value) {
            addCriterion("f_card_no <", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noLessThanOrEqualTo(String value) {
            addCriterion("f_card_no <=", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noLike(String value) {
            addCriterion("f_card_no like", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noNotLike(String value) {
            addCriterion("f_card_no not like", value, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noIn(List<String> values) {
            addCriterion("f_card_no in", values, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noNotIn(List<String> values) {
            addCriterion("f_card_no not in", values, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noBetween(String value1, String value2) {
            addCriterion("f_card_no between", value1, value2, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_card_noNotBetween(String value1, String value2) {
            addCriterion("f_card_no not between", value1, value2, "f_card_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noIsNull() {
            addCriterion("f_citizen_id_no is null");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noIsNotNull() {
            addCriterion("f_citizen_id_no is not null");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noEqualTo(String value) {
            addCriterion("f_citizen_id_no =", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noNotEqualTo(String value) {
            addCriterion("f_citizen_id_no <>", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noGreaterThan(String value) {
            addCriterion("f_citizen_id_no >", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_citizen_id_no >=", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noLessThan(String value) {
            addCriterion("f_citizen_id_no <", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noLessThanOrEqualTo(String value) {
            addCriterion("f_citizen_id_no <=", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noLike(String value) {
            addCriterion("f_citizen_id_no like", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noNotLike(String value) {
            addCriterion("f_citizen_id_no not like", value, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noIn(List<String> values) {
            addCriterion("f_citizen_id_no in", values, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noNotIn(List<String> values) {
            addCriterion("f_citizen_id_no not in", values, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noBetween(String value1, String value2) {
            addCriterion("f_citizen_id_no between", value1, value2, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_noNotBetween(String value1, String value2) {
            addCriterion("f_citizen_id_no not between", value1, value2, "f_citizen_id_no");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1IsNull() {
            addCriterion("f_citizen_id_img1 is null");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1IsNotNull() {
            addCriterion("f_citizen_id_img1 is not null");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1EqualTo(String value) {
            addCriterion("f_citizen_id_img1 =", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1NotEqualTo(String value) {
            addCriterion("f_citizen_id_img1 <>", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1GreaterThan(String value) {
            addCriterion("f_citizen_id_img1 >", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1GreaterThanOrEqualTo(String value) {
            addCriterion("f_citizen_id_img1 >=", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1LessThan(String value) {
            addCriterion("f_citizen_id_img1 <", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1LessThanOrEqualTo(String value) {
            addCriterion("f_citizen_id_img1 <=", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1Like(String value) {
            addCriterion("f_citizen_id_img1 like", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1NotLike(String value) {
            addCriterion("f_citizen_id_img1 not like", value, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1In(List<String> values) {
            addCriterion("f_citizen_id_img1 in", values, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1NotIn(List<String> values) {
            addCriterion("f_citizen_id_img1 not in", values, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1Between(String value1, String value2) {
            addCriterion("f_citizen_id_img1 between", value1, value2, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img1NotBetween(String value1, String value2) {
            addCriterion("f_citizen_id_img1 not between", value1, value2, "f_citizen_id_img1");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2IsNull() {
            addCriterion("f_citizen_id_img2 is null");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2IsNotNull() {
            addCriterion("f_citizen_id_img2 is not null");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2EqualTo(String value) {
            addCriterion("f_citizen_id_img2 =", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2NotEqualTo(String value) {
            addCriterion("f_citizen_id_img2 <>", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2GreaterThan(String value) {
            addCriterion("f_citizen_id_img2 >", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2GreaterThanOrEqualTo(String value) {
            addCriterion("f_citizen_id_img2 >=", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2LessThan(String value) {
            addCriterion("f_citizen_id_img2 <", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2LessThanOrEqualTo(String value) {
            addCriterion("f_citizen_id_img2 <=", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2Like(String value) {
            addCriterion("f_citizen_id_img2 like", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2NotLike(String value) {
            addCriterion("f_citizen_id_img2 not like", value, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2In(List<String> values) {
            addCriterion("f_citizen_id_img2 in", values, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2NotIn(List<String> values) {
            addCriterion("f_citizen_id_img2 not in", values, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2Between(String value1, String value2) {
            addCriterion("f_citizen_id_img2 between", value1, value2, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_citizen_id_img2NotBetween(String value1, String value2) {
            addCriterion("f_citizen_id_img2 not between", value1, value2, "f_citizen_id_img2");
            return (Criteria) this;
        }

        public Criteria andF_creator_idIsNull() {
            addCriterion("f_creator_id is null");
            return (Criteria) this;
        }

        public Criteria andF_creator_idIsNotNull() {
            addCriterion("f_creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_creator_idEqualTo(Integer value) {
            addCriterion("f_creator_id =", value, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idNotEqualTo(Integer value) {
            addCriterion("f_creator_id <>", value, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idGreaterThan(Integer value) {
            addCriterion("f_creator_id >", value, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_creator_id >=", value, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idLessThan(Integer value) {
            addCriterion("f_creator_id <", value, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_creator_id <=", value, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idIn(List<Integer> values) {
            addCriterion("f_creator_id in", values, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idNotIn(List<Integer> values) {
            addCriterion("f_creator_id not in", values, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idBetween(Integer value1, Integer value2) {
            addCriterion("f_creator_id between", value1, value2, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_creator_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_creator_id not between", value1, value2, "f_creator_id");
            return (Criteria) this;
        }

        public Criteria andF_create_timeIsNull() {
            addCriterion("f_create_time is null");
            return (Criteria) this;
        }

        public Criteria andF_create_timeIsNotNull() {
            addCriterion("f_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andF_create_timeEqualTo(Date value) {
            addCriterion("f_create_time =", value, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeNotEqualTo(Date value) {
            addCriterion("f_create_time <>", value, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeGreaterThan(Date value) {
            addCriterion("f_create_time >", value, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_create_time >=", value, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeLessThan(Date value) {
            addCriterion("f_create_time <", value, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeLessThanOrEqualTo(Date value) {
            addCriterion("f_create_time <=", value, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeIn(List<Date> values) {
            addCriterion("f_create_time in", values, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeNotIn(List<Date> values) {
            addCriterion("f_create_time not in", values, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeBetween(Date value1, Date value2) {
            addCriterion("f_create_time between", value1, value2, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_create_timeNotBetween(Date value1, Date value2) {
            addCriterion("f_create_time not between", value1, value2, "f_create_time");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personIsNull() {
            addCriterion("f_recruitment_person is null");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personIsNotNull() {
            addCriterion("f_recruitment_person is not null");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personEqualTo(String value) {
            addCriterion("f_recruitment_person =", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personNotEqualTo(String value) {
            addCriterion("f_recruitment_person <>", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personGreaterThan(String value) {
            addCriterion("f_recruitment_person >", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personGreaterThanOrEqualTo(String value) {
            addCriterion("f_recruitment_person >=", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personLessThan(String value) {
            addCriterion("f_recruitment_person <", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personLessThanOrEqualTo(String value) {
            addCriterion("f_recruitment_person <=", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personLike(String value) {
            addCriterion("f_recruitment_person like", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personNotLike(String value) {
            addCriterion("f_recruitment_person not like", value, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personIn(List<String> values) {
            addCriterion("f_recruitment_person in", values, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personNotIn(List<String> values) {
            addCriterion("f_recruitment_person not in", values, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personBetween(String value1, String value2) {
            addCriterion("f_recruitment_person between", value1, value2, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_personNotBetween(String value1, String value2) {
            addCriterion("f_recruitment_person not between", value1, value2, "f_recruitment_person");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathIsNull() {
            addCriterion("f_recruitment_path is null");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathIsNotNull() {
            addCriterion("f_recruitment_path is not null");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathEqualTo(String value) {
            addCriterion("f_recruitment_path =", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathNotEqualTo(String value) {
            addCriterion("f_recruitment_path <>", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathGreaterThan(String value) {
            addCriterion("f_recruitment_path >", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathGreaterThanOrEqualTo(String value) {
            addCriterion("f_recruitment_path >=", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathLessThan(String value) {
            addCriterion("f_recruitment_path <", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathLessThanOrEqualTo(String value) {
            addCriterion("f_recruitment_path <=", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathLike(String value) {
            addCriterion("f_recruitment_path like", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathNotLike(String value) {
            addCriterion("f_recruitment_path not like", value, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathIn(List<String> values) {
            addCriterion("f_recruitment_path in", values, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathNotIn(List<String> values) {
            addCriterion("f_recruitment_path not in", values, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathBetween(String value1, String value2) {
            addCriterion("f_recruitment_path between", value1, value2, "f_recruitment_path");
            return (Criteria) this;
        }

        public Criteria andF_recruitment_pathNotBetween(String value1, String value2) {
            addCriterion("f_recruitment_path not between", value1, value2, "f_recruitment_path");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_factory_user
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 29 14:33:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_factory_user
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}