package com.example.hxyz.domain.entity;

import java.util.Date;

public class OrderComplainEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_create_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_end_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_status
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_complain_set
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String complain_set;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_director_handle
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String director_handle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_client_pleased
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String client_pleased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_order_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_order_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String order_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_factory_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer factory_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_user_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_handle_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String handle_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_handle_tel
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String handle_tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_handle_finish_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date handle_finish_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_client_reply_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date client_reply_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_client_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String client_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_manage_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String manage_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_manage_tel
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String manage_tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_manage_end_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Date manage_end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_complain_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String complain_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_money
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_cService_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String cService_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_director_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String director_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_complain.f_manager_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    private String manager_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_id
     *
     * @return the value of t_order_complain.f_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_id
     *
     * @param id the value for t_order_complain.f_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_create_time
     *
     * @return the value of t_order_complain.f_create_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_create_time
     *
     * @param create_time the value for t_order_complain.f_create_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_end_time
     *
     * @return the value of t_order_complain.f_end_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_end_time
     *
     * @param end_time the value for t_order_complain.f_end_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_status
     *
     * @return the value of t_order_complain.f_status
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_status
     *
     * @param status the value for t_order_complain.f_status
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_complain_set
     *
     * @return the value of t_order_complain.f_complain_set
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getComplain_set() {
        return complain_set;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_complain_set
     *
     * @param complain_set the value for t_order_complain.f_complain_set
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setComplain_set(String complain_set) {
        this.complain_set = complain_set;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_director_handle
     *
     * @return the value of t_order_complain.f_director_handle
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getDirector_handle() {
        return director_handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_director_handle
     *
     * @param director_handle the value for t_order_complain.f_director_handle
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setDirector_handle(String director_handle) {
        this.director_handle = director_handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_client_pleased
     *
     * @return the value of t_order_complain.f_client_pleased
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getClient_pleased() {
        return client_pleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_client_pleased
     *
     * @param client_pleased the value for t_order_complain.f_client_pleased
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setClient_pleased(String client_pleased) {
        this.client_pleased = client_pleased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_order_id
     *
     * @return the value of t_order_complain.f_order_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_order_id
     *
     * @param order_id the value for t_order_complain.f_order_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_order_no
     *
     * @return the value of t_order_complain.f_order_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getOrder_no() {
        return order_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_order_no
     *
     * @param order_no the value for t_order_complain.f_order_no
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setOrder_no(String order_no) {
        this.order_no = order_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_factory_id
     *
     * @return the value of t_order_complain.f_factory_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getFactory_id() {
        return factory_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_factory_id
     *
     * @param factory_id the value for t_order_complain.f_factory_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setFactory_id(Integer factory_id) {
        this.factory_id = factory_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_user_id
     *
     * @return the value of t_order_complain.f_user_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_user_id
     *
     * @param user_id the value for t_order_complain.f_user_id
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_handle_content
     *
     * @return the value of t_order_complain.f_handle_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getHandle_content() {
        return handle_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_handle_content
     *
     * @param handle_content the value for t_order_complain.f_handle_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setHandle_content(String handle_content) {
        this.handle_content = handle_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_handle_tel
     *
     * @return the value of t_order_complain.f_handle_tel
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getHandle_tel() {
        return handle_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_handle_tel
     *
     * @param handle_tel the value for t_order_complain.f_handle_tel
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setHandle_tel(String handle_tel) {
        this.handle_tel = handle_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_handle_finish_time
     *
     * @return the value of t_order_complain.f_handle_finish_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getHandle_finish_time() {
        return handle_finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_handle_finish_time
     *
     * @param handle_finish_time the value for t_order_complain.f_handle_finish_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setHandle_finish_time(Date handle_finish_time) {
        this.handle_finish_time = handle_finish_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_client_reply_time
     *
     * @return the value of t_order_complain.f_client_reply_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getClient_reply_time() {
        return client_reply_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_client_reply_time
     *
     * @param client_reply_time the value for t_order_complain.f_client_reply_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setClient_reply_time(Date client_reply_time) {
        this.client_reply_time = client_reply_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_client_content
     *
     * @return the value of t_order_complain.f_client_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getClient_content() {
        return client_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_client_content
     *
     * @param client_content the value for t_order_complain.f_client_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setClient_content(String client_content) {
        this.client_content = client_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_manage_content
     *
     * @return the value of t_order_complain.f_manage_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getManage_content() {
        return manage_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_manage_content
     *
     * @param manage_content the value for t_order_complain.f_manage_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setManage_content(String manage_content) {
        this.manage_content = manage_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_manage_tel
     *
     * @return the value of t_order_complain.f_manage_tel
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getManage_tel() {
        return manage_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_manage_tel
     *
     * @param manage_tel the value for t_order_complain.f_manage_tel
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setManage_tel(String manage_tel) {
        this.manage_tel = manage_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_manage_end_time
     *
     * @return the value of t_order_complain.f_manage_end_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Date getManage_end_time() {
        return manage_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_manage_end_time
     *
     * @param manage_end_time the value for t_order_complain.f_manage_end_time
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setManage_end_time(Date manage_end_time) {
        this.manage_end_time = manage_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_complain_content
     *
     * @return the value of t_order_complain.f_complain_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getComplain_content() {
        return complain_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_complain_content
     *
     * @param complain_content the value for t_order_complain.f_complain_content
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setComplain_content(String complain_content) {
        this.complain_content = complain_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_money
     *
     * @return the value of t_order_complain.f_money
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_money
     *
     * @param money the value for t_order_complain.f_money
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_cService_name
     *
     * @return the value of t_order_complain.f_cService_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getcService_name() {
        return cService_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_cService_name
     *
     * @param cService_name the value for t_order_complain.f_cService_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setcService_name(String cService_name) {
        this.cService_name = cService_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_director_name
     *
     * @return the value of t_order_complain.f_director_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getDirector_name() {
        return director_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_director_name
     *
     * @param director_name the value for t_order_complain.f_director_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setDirector_name(String director_name) {
        this.director_name = director_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_complain.f_manager_name
     *
     * @return the value of t_order_complain.f_manager_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getManager_name() {
        return manager_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_complain.f_manager_name
     *
     * @param manager_name the value for t_order_complain.f_manager_name
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setManager_name(String manager_name) {
        this.manager_name = manager_name;
    }
}