package com.example.hxyz.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderComplainEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public OrderComplainEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("f_create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("f_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("f_create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("f_create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("f_create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("f_create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("f_create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("f_create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("f_create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("f_create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("f_create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeIsNull() {
            addCriterion("f_end_time is null");
            return (Criteria) this;
        }

        public Criteria andEnd_timeIsNotNull() {
            addCriterion("f_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEnd_timeEqualTo(Date value) {
            addCriterion("f_end_time =", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeNotEqualTo(Date value) {
            addCriterion("f_end_time <>", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeGreaterThan(Date value) {
            addCriterion("f_end_time >", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_end_time >=", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeLessThan(Date value) {
            addCriterion("f_end_time <", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeLessThanOrEqualTo(Date value) {
            addCriterion("f_end_time <=", value, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeIn(List<Date> values) {
            addCriterion("f_end_time in", values, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeNotIn(List<Date> values) {
            addCriterion("f_end_time not in", values, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeBetween(Date value1, Date value2) {
            addCriterion("f_end_time between", value1, value2, "end_time");
            return (Criteria) this;
        }

        public Criteria andEnd_timeNotBetween(Date value1, Date value2) {
            addCriterion("f_end_time not between", value1, value2, "end_time");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("f_status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("f_status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("f_status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("f_status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("f_status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("f_status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("f_status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("f_status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("f_status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("f_status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("f_status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("f_status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andComplain_setIsNull() {
            addCriterion("f_complain_set is null");
            return (Criteria) this;
        }

        public Criteria andComplain_setIsNotNull() {
            addCriterion("f_complain_set is not null");
            return (Criteria) this;
        }

        public Criteria andComplain_setEqualTo(String value) {
            addCriterion("f_complain_set =", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setNotEqualTo(String value) {
            addCriterion("f_complain_set <>", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setGreaterThan(String value) {
            addCriterion("f_complain_set >", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setGreaterThanOrEqualTo(String value) {
            addCriterion("f_complain_set >=", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setLessThan(String value) {
            addCriterion("f_complain_set <", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setLessThanOrEqualTo(String value) {
            addCriterion("f_complain_set <=", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setLike(String value) {
            addCriterion("f_complain_set like", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setNotLike(String value) {
            addCriterion("f_complain_set not like", value, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setIn(List<String> values) {
            addCriterion("f_complain_set in", values, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setNotIn(List<String> values) {
            addCriterion("f_complain_set not in", values, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setBetween(String value1, String value2) {
            addCriterion("f_complain_set between", value1, value2, "complain_set");
            return (Criteria) this;
        }

        public Criteria andComplain_setNotBetween(String value1, String value2) {
            addCriterion("f_complain_set not between", value1, value2, "complain_set");
            return (Criteria) this;
        }

        public Criteria andDirector_handleIsNull() {
            addCriterion("f_director_handle is null");
            return (Criteria) this;
        }

        public Criteria andDirector_handleIsNotNull() {
            addCriterion("f_director_handle is not null");
            return (Criteria) this;
        }

        public Criteria andDirector_handleEqualTo(String value) {
            addCriterion("f_director_handle =", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleNotEqualTo(String value) {
            addCriterion("f_director_handle <>", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleGreaterThan(String value) {
            addCriterion("f_director_handle >", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleGreaterThanOrEqualTo(String value) {
            addCriterion("f_director_handle >=", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleLessThan(String value) {
            addCriterion("f_director_handle <", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleLessThanOrEqualTo(String value) {
            addCriterion("f_director_handle <=", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleLike(String value) {
            addCriterion("f_director_handle like", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleNotLike(String value) {
            addCriterion("f_director_handle not like", value, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleIn(List<String> values) {
            addCriterion("f_director_handle in", values, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleNotIn(List<String> values) {
            addCriterion("f_director_handle not in", values, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleBetween(String value1, String value2) {
            addCriterion("f_director_handle between", value1, value2, "director_handle");
            return (Criteria) this;
        }

        public Criteria andDirector_handleNotBetween(String value1, String value2) {
            addCriterion("f_director_handle not between", value1, value2, "director_handle");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedIsNull() {
            addCriterion("f_client_pleased is null");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedIsNotNull() {
            addCriterion("f_client_pleased is not null");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedEqualTo(String value) {
            addCriterion("f_client_pleased =", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedNotEqualTo(String value) {
            addCriterion("f_client_pleased <>", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedGreaterThan(String value) {
            addCriterion("f_client_pleased >", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedGreaterThanOrEqualTo(String value) {
            addCriterion("f_client_pleased >=", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedLessThan(String value) {
            addCriterion("f_client_pleased <", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedLessThanOrEqualTo(String value) {
            addCriterion("f_client_pleased <=", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedLike(String value) {
            addCriterion("f_client_pleased like", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedNotLike(String value) {
            addCriterion("f_client_pleased not like", value, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedIn(List<String> values) {
            addCriterion("f_client_pleased in", values, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedNotIn(List<String> values) {
            addCriterion("f_client_pleased not in", values, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedBetween(String value1, String value2) {
            addCriterion("f_client_pleased between", value1, value2, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andClient_pleasedNotBetween(String value1, String value2) {
            addCriterion("f_client_pleased not between", value1, value2, "client_pleased");
            return (Criteria) this;
        }

        public Criteria andOrder_idIsNull() {
            addCriterion("f_order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrder_idIsNotNull() {
            addCriterion("f_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_idEqualTo(Integer value) {
            addCriterion("f_order_id =", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotEqualTo(Integer value) {
            addCriterion("f_order_id <>", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idGreaterThan(Integer value) {
            addCriterion("f_order_id >", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_order_id >=", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idLessThan(Integer value) {
            addCriterion("f_order_id <", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_order_id <=", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idIn(List<Integer> values) {
            addCriterion("f_order_id in", values, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotIn(List<Integer> values) {
            addCriterion("f_order_id not in", values, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idBetween(Integer value1, Integer value2) {
            addCriterion("f_order_id between", value1, value2, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_order_id not between", value1, value2, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_noIsNull() {
            addCriterion("f_order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrder_noIsNotNull() {
            addCriterion("f_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_noEqualTo(String value) {
            addCriterion("f_order_no =", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotEqualTo(String value) {
            addCriterion("f_order_no <>", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noGreaterThan(String value) {
            addCriterion("f_order_no >", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_order_no >=", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLessThan(String value) {
            addCriterion("f_order_no <", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLessThanOrEqualTo(String value) {
            addCriterion("f_order_no <=", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLike(String value) {
            addCriterion("f_order_no like", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotLike(String value) {
            addCriterion("f_order_no not like", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noIn(List<String> values) {
            addCriterion("f_order_no in", values, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotIn(List<String> values) {
            addCriterion("f_order_no not in", values, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noBetween(String value1, String value2) {
            addCriterion("f_order_no between", value1, value2, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotBetween(String value1, String value2) {
            addCriterion("f_order_no not between", value1, value2, "order_no");
            return (Criteria) this;
        }

        public Criteria andFactory_idIsNull() {
            addCriterion("f_factory_id is null");
            return (Criteria) this;
        }

        public Criteria andFactory_idIsNotNull() {
            addCriterion("f_factory_id is not null");
            return (Criteria) this;
        }

        public Criteria andFactory_idEqualTo(Integer value) {
            addCriterion("f_factory_id =", value, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idNotEqualTo(Integer value) {
            addCriterion("f_factory_id <>", value, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idGreaterThan(Integer value) {
            addCriterion("f_factory_id >", value, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_factory_id >=", value, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idLessThan(Integer value) {
            addCriterion("f_factory_id <", value, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_factory_id <=", value, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idIn(List<Integer> values) {
            addCriterion("f_factory_id in", values, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idNotIn(List<Integer> values) {
            addCriterion("f_factory_id not in", values, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idBetween(Integer value1, Integer value2) {
            addCriterion("f_factory_id between", value1, value2, "factory_id");
            return (Criteria) this;
        }

        public Criteria andFactory_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_factory_id not between", value1, value2, "factory_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNull() {
            addCriterion("f_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("f_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Integer value) {
            addCriterion("f_user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Integer value) {
            addCriterion("f_user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Integer value) {
            addCriterion("f_user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Integer value) {
            addCriterion("f_user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Integer> values) {
            addCriterion("f_user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Integer> values) {
            addCriterion("f_user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Integer value1, Integer value2) {
            addCriterion("f_user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andHandle_contentIsNull() {
            addCriterion("f_handle_content is null");
            return (Criteria) this;
        }

        public Criteria andHandle_contentIsNotNull() {
            addCriterion("f_handle_content is not null");
            return (Criteria) this;
        }

        public Criteria andHandle_contentEqualTo(String value) {
            addCriterion("f_handle_content =", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentNotEqualTo(String value) {
            addCriterion("f_handle_content <>", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentGreaterThan(String value) {
            addCriterion("f_handle_content >", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentGreaterThanOrEqualTo(String value) {
            addCriterion("f_handle_content >=", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentLessThan(String value) {
            addCriterion("f_handle_content <", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentLessThanOrEqualTo(String value) {
            addCriterion("f_handle_content <=", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentLike(String value) {
            addCriterion("f_handle_content like", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentNotLike(String value) {
            addCriterion("f_handle_content not like", value, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentIn(List<String> values) {
            addCriterion("f_handle_content in", values, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentNotIn(List<String> values) {
            addCriterion("f_handle_content not in", values, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentBetween(String value1, String value2) {
            addCriterion("f_handle_content between", value1, value2, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_contentNotBetween(String value1, String value2) {
            addCriterion("f_handle_content not between", value1, value2, "handle_content");
            return (Criteria) this;
        }

        public Criteria andHandle_telIsNull() {
            addCriterion("f_handle_tel is null");
            return (Criteria) this;
        }

        public Criteria andHandle_telIsNotNull() {
            addCriterion("f_handle_tel is not null");
            return (Criteria) this;
        }

        public Criteria andHandle_telEqualTo(String value) {
            addCriterion("f_handle_tel =", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telNotEqualTo(String value) {
            addCriterion("f_handle_tel <>", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telGreaterThan(String value) {
            addCriterion("f_handle_tel >", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telGreaterThanOrEqualTo(String value) {
            addCriterion("f_handle_tel >=", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telLessThan(String value) {
            addCriterion("f_handle_tel <", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telLessThanOrEqualTo(String value) {
            addCriterion("f_handle_tel <=", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telLike(String value) {
            addCriterion("f_handle_tel like", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telNotLike(String value) {
            addCriterion("f_handle_tel not like", value, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telIn(List<String> values) {
            addCriterion("f_handle_tel in", values, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telNotIn(List<String> values) {
            addCriterion("f_handle_tel not in", values, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telBetween(String value1, String value2) {
            addCriterion("f_handle_tel between", value1, value2, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_telNotBetween(String value1, String value2) {
            addCriterion("f_handle_tel not between", value1, value2, "handle_tel");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeIsNull() {
            addCriterion("f_handle_finish_time is null");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeIsNotNull() {
            addCriterion("f_handle_finish_time is not null");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeEqualTo(Date value) {
            addCriterion("f_handle_finish_time =", value, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeNotEqualTo(Date value) {
            addCriterion("f_handle_finish_time <>", value, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeGreaterThan(Date value) {
            addCriterion("f_handle_finish_time >", value, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_handle_finish_time >=", value, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeLessThan(Date value) {
            addCriterion("f_handle_finish_time <", value, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeLessThanOrEqualTo(Date value) {
            addCriterion("f_handle_finish_time <=", value, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeIn(List<Date> values) {
            addCriterion("f_handle_finish_time in", values, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeNotIn(List<Date> values) {
            addCriterion("f_handle_finish_time not in", values, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeBetween(Date value1, Date value2) {
            addCriterion("f_handle_finish_time between", value1, value2, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andHandle_finish_timeNotBetween(Date value1, Date value2) {
            addCriterion("f_handle_finish_time not between", value1, value2, "handle_finish_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeIsNull() {
            addCriterion("f_client_reply_time is null");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeIsNotNull() {
            addCriterion("f_client_reply_time is not null");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeEqualTo(Date value) {
            addCriterion("f_client_reply_time =", value, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeNotEqualTo(Date value) {
            addCriterion("f_client_reply_time <>", value, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeGreaterThan(Date value) {
            addCriterion("f_client_reply_time >", value, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_client_reply_time >=", value, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeLessThan(Date value) {
            addCriterion("f_client_reply_time <", value, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeLessThanOrEqualTo(Date value) {
            addCriterion("f_client_reply_time <=", value, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeIn(List<Date> values) {
            addCriterion("f_client_reply_time in", values, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeNotIn(List<Date> values) {
            addCriterion("f_client_reply_time not in", values, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeBetween(Date value1, Date value2) {
            addCriterion("f_client_reply_time between", value1, value2, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_reply_timeNotBetween(Date value1, Date value2) {
            addCriterion("f_client_reply_time not between", value1, value2, "client_reply_time");
            return (Criteria) this;
        }

        public Criteria andClient_contentIsNull() {
            addCriterion("f_client_content is null");
            return (Criteria) this;
        }

        public Criteria andClient_contentIsNotNull() {
            addCriterion("f_client_content is not null");
            return (Criteria) this;
        }

        public Criteria andClient_contentEqualTo(String value) {
            addCriterion("f_client_content =", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentNotEqualTo(String value) {
            addCriterion("f_client_content <>", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentGreaterThan(String value) {
            addCriterion("f_client_content >", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentGreaterThanOrEqualTo(String value) {
            addCriterion("f_client_content >=", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentLessThan(String value) {
            addCriterion("f_client_content <", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentLessThanOrEqualTo(String value) {
            addCriterion("f_client_content <=", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentLike(String value) {
            addCriterion("f_client_content like", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentNotLike(String value) {
            addCriterion("f_client_content not like", value, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentIn(List<String> values) {
            addCriterion("f_client_content in", values, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentNotIn(List<String> values) {
            addCriterion("f_client_content not in", values, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentBetween(String value1, String value2) {
            addCriterion("f_client_content between", value1, value2, "client_content");
            return (Criteria) this;
        }

        public Criteria andClient_contentNotBetween(String value1, String value2) {
            addCriterion("f_client_content not between", value1, value2, "client_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentIsNull() {
            addCriterion("f_manage_content is null");
            return (Criteria) this;
        }

        public Criteria andManage_contentIsNotNull() {
            addCriterion("f_manage_content is not null");
            return (Criteria) this;
        }

        public Criteria andManage_contentEqualTo(String value) {
            addCriterion("f_manage_content =", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentNotEqualTo(String value) {
            addCriterion("f_manage_content <>", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentGreaterThan(String value) {
            addCriterion("f_manage_content >", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentGreaterThanOrEqualTo(String value) {
            addCriterion("f_manage_content >=", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentLessThan(String value) {
            addCriterion("f_manage_content <", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentLessThanOrEqualTo(String value) {
            addCriterion("f_manage_content <=", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentLike(String value) {
            addCriterion("f_manage_content like", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentNotLike(String value) {
            addCriterion("f_manage_content not like", value, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentIn(List<String> values) {
            addCriterion("f_manage_content in", values, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentNotIn(List<String> values) {
            addCriterion("f_manage_content not in", values, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentBetween(String value1, String value2) {
            addCriterion("f_manage_content between", value1, value2, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_contentNotBetween(String value1, String value2) {
            addCriterion("f_manage_content not between", value1, value2, "manage_content");
            return (Criteria) this;
        }

        public Criteria andManage_telIsNull() {
            addCriterion("f_manage_tel is null");
            return (Criteria) this;
        }

        public Criteria andManage_telIsNotNull() {
            addCriterion("f_manage_tel is not null");
            return (Criteria) this;
        }

        public Criteria andManage_telEqualTo(String value) {
            addCriterion("f_manage_tel =", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telNotEqualTo(String value) {
            addCriterion("f_manage_tel <>", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telGreaterThan(String value) {
            addCriterion("f_manage_tel >", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telGreaterThanOrEqualTo(String value) {
            addCriterion("f_manage_tel >=", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telLessThan(String value) {
            addCriterion("f_manage_tel <", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telLessThanOrEqualTo(String value) {
            addCriterion("f_manage_tel <=", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telLike(String value) {
            addCriterion("f_manage_tel like", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telNotLike(String value) {
            addCriterion("f_manage_tel not like", value, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telIn(List<String> values) {
            addCriterion("f_manage_tel in", values, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telNotIn(List<String> values) {
            addCriterion("f_manage_tel not in", values, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telBetween(String value1, String value2) {
            addCriterion("f_manage_tel between", value1, value2, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_telNotBetween(String value1, String value2) {
            addCriterion("f_manage_tel not between", value1, value2, "manage_tel");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeIsNull() {
            addCriterion("f_manage_end_time is null");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeIsNotNull() {
            addCriterion("f_manage_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeEqualTo(Date value) {
            addCriterion("f_manage_end_time =", value, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeNotEqualTo(Date value) {
            addCriterion("f_manage_end_time <>", value, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeGreaterThan(Date value) {
            addCriterion("f_manage_end_time >", value, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("f_manage_end_time >=", value, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeLessThan(Date value) {
            addCriterion("f_manage_end_time <", value, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeLessThanOrEqualTo(Date value) {
            addCriterion("f_manage_end_time <=", value, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeIn(List<Date> values) {
            addCriterion("f_manage_end_time in", values, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeNotIn(List<Date> values) {
            addCriterion("f_manage_end_time not in", values, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeBetween(Date value1, Date value2) {
            addCriterion("f_manage_end_time between", value1, value2, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andManage_end_timeNotBetween(Date value1, Date value2) {
            addCriterion("f_manage_end_time not between", value1, value2, "manage_end_time");
            return (Criteria) this;
        }

        public Criteria andComplain_contentIsNull() {
            addCriterion("f_complain_content is null");
            return (Criteria) this;
        }

        public Criteria andComplain_contentIsNotNull() {
            addCriterion("f_complain_content is not null");
            return (Criteria) this;
        }

        public Criteria andComplain_contentEqualTo(String value) {
            addCriterion("f_complain_content =", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentNotEqualTo(String value) {
            addCriterion("f_complain_content <>", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentGreaterThan(String value) {
            addCriterion("f_complain_content >", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentGreaterThanOrEqualTo(String value) {
            addCriterion("f_complain_content >=", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentLessThan(String value) {
            addCriterion("f_complain_content <", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentLessThanOrEqualTo(String value) {
            addCriterion("f_complain_content <=", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentLike(String value) {
            addCriterion("f_complain_content like", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentNotLike(String value) {
            addCriterion("f_complain_content not like", value, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentIn(List<String> values) {
            addCriterion("f_complain_content in", values, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentNotIn(List<String> values) {
            addCriterion("f_complain_content not in", values, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentBetween(String value1, String value2) {
            addCriterion("f_complain_content between", value1, value2, "complain_content");
            return (Criteria) this;
        }

        public Criteria andComplain_contentNotBetween(String value1, String value2) {
            addCriterion("f_complain_content not between", value1, value2, "complain_content");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("f_money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("f_money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(Integer value) {
            addCriterion("f_money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(Integer value) {
            addCriterion("f_money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(Integer value) {
            addCriterion("f_money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(Integer value) {
            addCriterion("f_money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(Integer value) {
            addCriterion("f_money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<Integer> values) {
            addCriterion("f_money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<Integer> values) {
            addCriterion("f_money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(Integer value1, Integer value2) {
            addCriterion("f_money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("f_money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andCService_nameIsNull() {
            addCriterion("f_cService_name is null");
            return (Criteria) this;
        }

        public Criteria andCService_nameIsNotNull() {
            addCriterion("f_cService_name is not null");
            return (Criteria) this;
        }

        public Criteria andCService_nameEqualTo(String value) {
            addCriterion("f_cService_name =", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameNotEqualTo(String value) {
            addCriterion("f_cService_name <>", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameGreaterThan(String value) {
            addCriterion("f_cService_name >", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_cService_name >=", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameLessThan(String value) {
            addCriterion("f_cService_name <", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameLessThanOrEqualTo(String value) {
            addCriterion("f_cService_name <=", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameLike(String value) {
            addCriterion("f_cService_name like", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameNotLike(String value) {
            addCriterion("f_cService_name not like", value, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameIn(List<String> values) {
            addCriterion("f_cService_name in", values, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameNotIn(List<String> values) {
            addCriterion("f_cService_name not in", values, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameBetween(String value1, String value2) {
            addCriterion("f_cService_name between", value1, value2, "cService_name");
            return (Criteria) this;
        }

        public Criteria andCService_nameNotBetween(String value1, String value2) {
            addCriterion("f_cService_name not between", value1, value2, "cService_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameIsNull() {
            addCriterion("f_director_name is null");
            return (Criteria) this;
        }

        public Criteria andDirector_nameIsNotNull() {
            addCriterion("f_director_name is not null");
            return (Criteria) this;
        }

        public Criteria andDirector_nameEqualTo(String value) {
            addCriterion("f_director_name =", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameNotEqualTo(String value) {
            addCriterion("f_director_name <>", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameGreaterThan(String value) {
            addCriterion("f_director_name >", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_director_name >=", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameLessThan(String value) {
            addCriterion("f_director_name <", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameLessThanOrEqualTo(String value) {
            addCriterion("f_director_name <=", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameLike(String value) {
            addCriterion("f_director_name like", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameNotLike(String value) {
            addCriterion("f_director_name not like", value, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameIn(List<String> values) {
            addCriterion("f_director_name in", values, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameNotIn(List<String> values) {
            addCriterion("f_director_name not in", values, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameBetween(String value1, String value2) {
            addCriterion("f_director_name between", value1, value2, "director_name");
            return (Criteria) this;
        }

        public Criteria andDirector_nameNotBetween(String value1, String value2) {
            addCriterion("f_director_name not between", value1, value2, "director_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameIsNull() {
            addCriterion("f_manager_name is null");
            return (Criteria) this;
        }

        public Criteria andManager_nameIsNotNull() {
            addCriterion("f_manager_name is not null");
            return (Criteria) this;
        }

        public Criteria andManager_nameEqualTo(String value) {
            addCriterion("f_manager_name =", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameNotEqualTo(String value) {
            addCriterion("f_manager_name <>", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameGreaterThan(String value) {
            addCriterion("f_manager_name >", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_manager_name >=", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameLessThan(String value) {
            addCriterion("f_manager_name <", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameLessThanOrEqualTo(String value) {
            addCriterion("f_manager_name <=", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameLike(String value) {
            addCriterion("f_manager_name like", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameNotLike(String value) {
            addCriterion("f_manager_name not like", value, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameIn(List<String> values) {
            addCriterion("f_manager_name in", values, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameNotIn(List<String> values) {
            addCriterion("f_manager_name not in", values, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameBetween(String value1, String value2) {
            addCriterion("f_manager_name between", value1, value2, "manager_name");
            return (Criteria) this;
        }

        public Criteria andManager_nameNotBetween(String value1, String value2) {
            addCriterion("f_manager_name not between", value1, value2, "manager_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_complain
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 29 14:33:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}