package com.example.hxyz.domain.mapper;

import com.example.hxyz.assess.persistant.repository.MyBatisRepository;
import com.example.hxyz.domain.entity.OrderComplainEntity;
import com.example.hxyz.domain.entity.OrderComplainEntityExample;

import java.io.Serializable;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
@MyBatisRepository
public interface OrderComplainEntityMapper extends Serializable {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    int countByExample(OrderComplainEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    int deleteByExample(OrderComplainEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    @Delete({
        "delete from t_order_complain",
        "where f_id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    @Insert({
        "insert into t_order_complain (f_create_time, f_end_time, ",
        "f_status, f_complain_set, ",
        "f_director_handle, f_client_pleased, ",
        "f_order_id, f_order_no, ",
        "f_factory_id, f_user_id, ",
        "f_handle_content, f_handle_tel, ",
        "f_handle_finish_time, f_client_reply_time, ",
        "f_client_content, f_manage_content, ",
        "f_manage_tel, f_manage_end_time, ",
        "f_complain_content, f_money, ",
        "f_cService_name, f_director_name, ",
        "f_manager_name)",
        "values (#{create_time,jdbcType=TIMESTAMP}, #{end_time,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=VARCHAR}, #{complain_set,jdbcType=VARCHAR}, ",
        "#{director_handle,jdbcType=VARCHAR}, #{client_pleased,jdbcType=VARCHAR}, ",
        "#{order_id,jdbcType=INTEGER}, #{order_no,jdbcType=VARCHAR}, ",
        "#{factory_id,jdbcType=INTEGER}, #{user_id,jdbcType=INTEGER}, ",
        "#{handle_content,jdbcType=VARCHAR}, #{handle_tel,jdbcType=VARCHAR}, ",
        "#{handle_finish_time,jdbcType=TIMESTAMP}, #{client_reply_time,jdbcType=TIMESTAMP}, ",
        "#{client_content,jdbcType=VARCHAR}, #{manage_content,jdbcType=VARCHAR}, ",
        "#{manage_tel,jdbcType=VARCHAR}, #{manage_end_time,jdbcType=TIMESTAMP}, ",
        "#{complain_content,jdbcType=VARCHAR}, #{money,jdbcType=INTEGER}, ",
        "#{cService_name,jdbcType=VARCHAR}, #{director_name,jdbcType=VARCHAR}, ",
        "#{manager_name,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(OrderComplainEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    int insertSelective(OrderComplainEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    List<OrderComplainEntity> selectByExample(OrderComplainEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    @Select({
        "select",
        "f_id, f_create_time, f_end_time, f_status, f_complain_set, f_director_handle, ",
        "f_client_pleased, f_order_id, f_order_no, f_factory_id, f_user_id, f_handle_content, ",
        "f_handle_tel, f_handle_finish_time, f_client_reply_time, f_client_content, f_manage_content, ",
        "f_manage_tel, f_manage_end_time, f_complain_content, f_money, f_cService_name, ",
        "f_director_name, f_manager_name",
        "from t_order_complain",
        "where f_id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    OrderComplainEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderComplainEntity record, @Param("example") OrderComplainEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    int updateByExample(@Param("record") OrderComplainEntity record, @Param("example") OrderComplainEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    int updateByPrimaryKeySelective(OrderComplainEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_complain
     *
     * @mbggenerated Wed Mar 29 14:33:03 CST 2017
     */
    @Update({
        "update t_order_complain",
        "set f_create_time = #{create_time,jdbcType=TIMESTAMP},",
          "f_end_time = #{end_time,jdbcType=TIMESTAMP},",
          "f_status = #{status,jdbcType=VARCHAR},",
          "f_complain_set = #{complain_set,jdbcType=VARCHAR},",
          "f_director_handle = #{director_handle,jdbcType=VARCHAR},",
          "f_client_pleased = #{client_pleased,jdbcType=VARCHAR},",
          "f_order_id = #{order_id,jdbcType=INTEGER},",
          "f_order_no = #{order_no,jdbcType=VARCHAR},",
          "f_factory_id = #{factory_id,jdbcType=INTEGER},",
          "f_user_id = #{user_id,jdbcType=INTEGER},",
          "f_handle_content = #{handle_content,jdbcType=VARCHAR},",
          "f_handle_tel = #{handle_tel,jdbcType=VARCHAR},",
          "f_handle_finish_time = #{handle_finish_time,jdbcType=TIMESTAMP},",
          "f_client_reply_time = #{client_reply_time,jdbcType=TIMESTAMP},",
          "f_client_content = #{client_content,jdbcType=VARCHAR},",
          "f_manage_content = #{manage_content,jdbcType=VARCHAR},",
          "f_manage_tel = #{manage_tel,jdbcType=VARCHAR},",
          "f_manage_end_time = #{manage_end_time,jdbcType=TIMESTAMP},",
          "f_complain_content = #{complain_content,jdbcType=VARCHAR},",
          "f_money = #{money,jdbcType=INTEGER},",
          "f_cService_name = #{cService_name,jdbcType=VARCHAR},",
          "f_director_name = #{director_name,jdbcType=VARCHAR},",
          "f_manager_name = #{manager_name,jdbcType=VARCHAR}",
        "where f_id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderComplainEntity record);
}